### PR TITLE
Remove square-bracket subsetting from data lessons

### PR DESCRIPTION
**Pull request by ateucher**
As per the discussions in #89 , here is a pull request containing changes that remove square-bracket subsetting from the data lessons (04 and 05).

In addition, I:
- replaced `read.table` with `read.csv`, 
- added a bit of an introduction to classes (very basic), 
- made `cats$likes_string` with 1s and 0s instead of `TRUE` and `FALSE` to help illustrate coercion.

Things I didn't do:
- edit the introduction lesson to introduce function usage
- get rid of `rbind` and `cbind`
- rework subsetting lesson. I think it still works as is, but it might be worth having another look at it, and potentially incorporate moar cats.

I'm happy to work on those things, but I don't think it will happen in the very near future. If this PR looks okay, I think the overall R lesson will still work (though it would probably be worth a closer look) ... then I (or somebody else) can do those things if they are deemed necessary.

### CODE REVIEW

**Comment by naupaka** [comment]
@ateucher thanks for the PR!  We just merged some pretty substantial changes to the data type lessons, and now there are a bunch of merge conflicts with your PR. If you can pull the current version and add your changes on top of that, I'd be happy to merge this in. It may also be that some of your changes are now redundant with the improvements to the lessons. Or if you think the new versions of the lessons are OK and additional changes are unnecessary, then I will close this PR.

**Comment by aammd** [comment]
@ateucher @naupaka I'm going to re-examine this for merge conflicts with the most recent version of our lessons (i.e. a9dc3d6 )

**Comment by ateucher** [comment]
Yeah, sorry about that - I should have dealt with this then, as I'm sure there are many more changes since that have introduced even more conflicts...

**Comment by ateucher** [comment]
@aammd @naupaka @tomwright01 Since there are so many other issues being fixed here today, I wonder if throwing this big one into the mix might make things a bit more difficult to track. Proposal: After the bug BBQ (which unfortunately I can't take part in today), I will revisit my PR, address any conflicts, then resubmit?

**Pull request closed without merging**
