### PR TITLE
Rm subset from data

### PR DESCRIPTION
**Pull request by aammd**
This PR corrects any merge conflicts in #95

### CODE REVIEW

**Comment by tomwright01** [comment]
This seems to be a very comprehensive PR, however there are some issues.

This is my first time dealing with PR's on this scale so please excuse me if I'm reading this wrong.

04-data-structures-part-1.Rmd (and part 2) seem to contain unresolved merge conflicts. Also only changes to .Rmd files should be submitted. This commit seems to contain .md and .html files as well.

**Comment by ateucher** [comment]
Since there are so many other issues being fixed here today, I wonder if throwing this big one into the mix might make things a bit more difficult to track. Proposal: After the bug BBQ (which unfortunately I can't take part in today), I will revisit my PR, address any conflicts, then resubmit?

**Comment by tomwright01** [comment]
Thanks Andy, I completely agree. Let me know if I can help out.

**Comment by ateucher** [comment]
Awesome, thanks Tom, and @aammd for working on this.

**Comment by aammd** [comment]
@tomwright01 and @ateucher , actually it wasn't so bad! Once I figured out the merge conflict stuff it was OK

**Comment by ateucher** [comment]
Cool, nice work @aammd! Looks good to me - in fact it doesn't look like there are any open PRs that this should conflict with (Except perhaps #140 and #144)...

**Pull request closed without merging**
