### PR TITLE
Define fuzzy search in episode 3 (seeking help)

### PR DESCRIPTION
**Pull request by habpippin**
Closes issue #657 by submitting pull request for suggested idea. I edited the suggestion in the issue for additional clarity. 
Before content:
Screen Shot 2021-01-11 at 7 21 22 PM
After content: (doesn't look exactly the same bc of the way I knit the document, should show up normally in lesson)
Screen Shot 2021-01-11 at 7 21 40 PM
Added lines 87-92:
Screen Shot 2021-01-11 at 7 22 18 PM

### CODE REVIEW

**Comment by jcoliver** [comment]
Thanks, @habpippin

**Comment by jcoliver** [comment]
@fmichonneau any ideas why this is failing? It seems to be a fatal error preventing a website build. The addition to the .Rmd file does not seem like it should cause this failure.

**Comment by fmichonneau** [comment]
Hi Jeff, sorry for the delay here...

the issues are related to small formatting issues with the lessons: https://github.com/swcarpentry/r-novice-gapminder/runs/1685623773 (mostly misspecifications of blockquote styles).

the lesson still builds but it would be good to address them soon.

**Comment by jcoliver** [comment]
Thanks for that information, @fmichonneau . We are content to ignore the warnings and merge regardless; however, the merged changes are _not_ showing up on the live site at [http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/index.html](http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/index.html). The build-website check apparently failed: [https://github.com/swcarpentry/r-novice-gapminder/actions/runs/479267050](https://github.com/swcarpentry/r-novice-gapminder/actions/runs/479267050).

**Pull request merged**
