### PR TITLE
added updated screen shots, clarified language about variable names, …

### PR DESCRIPTION
**Pull request by maggimars**
I added updated screenshots of the RStudio IDE so that the images match what students will see. In particular, this includes the terminal tab, which is referred to later in the lesson. 

I clarified language about naming variables and fixed some small typos throughout. 

I also added a section about managing packages from the Rstudio panel.

### CODE REVIEW

**Comment by jcoliver** [comment]
Thanks for this PR, @maggimars . Would you update the pull request to replace the image files, rather than _add_ two new ones? That is, instead of creating fig/01-rstudio-script-updated.png and fig/01-rstudio-updated.png, overwrite the original files (fig/01-rstudio-script.png and fig/01-rstudio.png, respectively). This would also necessitate reverting the links to original file names, too.

**Comment by jcoliver** [comment]
Why was this closed, @fmichonneau ?

**Comment by fmichonneau** [comment]
it got closed because the pull request was done against the `gh-pages` branch instead of the `master` branch.

**Comment by fmichonneau** [comment]
recreated in #636

**Pull request closed without merging**
