### PR TITLE
spacing, ifelse, and vectorized changes 

### PR DESCRIPTION
**Pull request by atheobold**
Added consistent spacing, explanation of ifelse error based on length of input vector, and advice on what to use if iteration order doesn't matter.

### CODE REVIEW

**Comment by jcoliver** [comment]
Thank you for the PR, @atheobold ! These are great clarifications. Could you update the PR and put the for loop syntax lead-in back? It's line 173 of the current version:

The basic structure of a `for()` loop is:

Which should appear right before
```{r, eval = FALSE}
for(iterator in set of values){
  do a thing
}
```

**Comment by jcoliver** [comment]
@fmichonneau this PR seems like the Travis build should be finished (it exited with status 0 according to the log). Any ideas why it's listed as not being completed?

**Comment by fmichonneau** [comment]
I'm not sure, it looks like a fluke with the API. I think it can be merged.

**Comment by jcoliver** [comment]
Thanks, @atheobold !

**Pull request merged**
