### PR TITLE
Issue #368

### PR DESCRIPTION
**Pull request by mzc9**

### CODE REVIEW

**Comment by mzc9** [comment]
Should I be removing the ./Rhistory?

**Comment by naupaka** [comment]
@mzc9 yes please do remove the .Rhistory file from this PR. Thanks!

**Comment by naupaka** [comment]
PR to address #368

**Comment by mzc9** [comment]
Removed it.  (I think?)  Sorry, new at this, so hope I did the correct thing.  If not, apologies.  If you let me know how to rectify it, I will do it asap

**Comment by naupaka** [comment]
Thanks!

**Pull request merged**
