### PR TITLE
Update style to v9.4.0

### PR DESCRIPTION
**Pull request by rgaiacs**
A few changes on style.
Need manual changes at CONTRIBUTING.md!

### CODE REVIEW

**Comment by naupaka** [comment]
Nope. What do we have to do re: "Need manual changes at CONTRIBUTING.md!"?

**Comment by rgaiacs** [comment]
> What do we have to do re: "Need manual changes at CONTRIBUTING.md!"?

https://github.com/swcarpentry/lesson-example/pull/186/files#diff-6a3371457528722a734f3c51d9238c13L72

**Comment by rgaiacs** [comment]
> do you mean we need to remove the duplicate "and" from CONTRIBUTING.md

Yes. No way that the script could do it.

> or are there more "manual" changes?

No more as far as I reckon.

**Comment by jcoliver** [comment]
Right then. Fix for CONTRIBUTING.md in #376 .

**Pull request merged**
