### PR TITLE
Removed First Person narrative from lessons (Issue #302)

### PR DESCRIPTION
**Pull request by CarrieBrown**
Edited lesson narrative to remove any first person references ("I" and "my"), except in the Objectives.

### CODE REVIEW

**Comment by CarrieBrown** [comment]
In reference to https://github.com/swcarpentry/r-novice-gapminder/issues/302

**Comment by jcoliver** [comment]
Thanks, @CarrieBrown ! We'll take a look at the PR.

**Comment by raynamharris** [comment]
I really like the idea of removing 1st person narrative. Thanks @CarrieBrown

**Comment by mawds** [comment]
Thanks for the PR.  Sorry it took so long to merge it. I fixed the conflicts in ae9410625fd0b1a999398f3e2613df69df45a853 and merged that

**Pull request closed without merging**
