### PR TITLE
modifications of gapminder lesson01

### PR DESCRIPTION
**Pull request by rmcd1024**

### CODE REVIEW

**Comment by rmcd1024** [comment]
Yes. Left it vague since we're not sure what the lesson numbering will be at this point.

**Comment by rmcd1024** [comment]
By the way, not sure how you two feel but I would discuss vectorization much sooner in the lesson plan. As soon as feasible.

**Comment by naupaka** [comment]
Hi @rmcd1024 thanks for these improvements! Can you submit a new pull request with just the `Rmd` files and not the rendered (`.md` and `.html` files)? This makes ti much easier to review the pull requests. Once they're merged, the maintainers rebuild the content.

**Comment by rmcd1024** [comment]
Hello! I'm new to git and didn't mean to submit a pull request to
swcarpentry, as I'm working in a group (swc-nw) for a bootcamp at
Northwestern. I think that for the time being we just wanted our changes to
be local there, although there maybe there's a linkage I don't understand.

At any rate, can you suggest a way to have the pull request include only
.Rmd files? Going forward, I would ignore .html and .md, but I'm not sure
how to get rid of them now that I've been tracking them.

Thanks,

Bob

**Comment by eddelbuettel** [comment]
@naupaka I think this pull request may have ended up in error here.  We are so far mostly trying to figure out how to commit _our local fork_ over at https://github.com/swc-nw/r-novice-gapminder/.  I'd say feel free to close this one.

**Comment by naupaka** [comment]
Thanks @eddelbuettel and @rmcd1024 - I'll close this pull request for now, but in the future we'd welcome improvements to the lessons here too if you'd like to contribute them. Removing the files from your commit history would be rather complicated ([SO answer here](http://stackoverflow.com/questions/307828/completely-remove-file-from-all-git-repository-commit-history)), so probably easiest just to make a commit removing the derived files.

**Comment by rmcd1024** [comment]
Yes. Sorry for the confusion and thanks.

On Sun, Aug 9, 2015 at 11:02 PM, Naupaka Zimmerman <notifications@github.com

**Pull request closed without merging**
