### PR TITLE
Canonicalize CRAN links

### PR DESCRIPTION
**Pull request by katrinleinweber**
CRAN [asks people](https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-URLs) to use this URL variant when linking to packages ;-) This PR results from a semi-automatic search-and-replace script and implements their suggestion.

### CODE REVIEW

**Comment by jcoliver** [comment]
Thanks @katrinleinweber ! Looks good. Will merge pending successful Travis CI build.

**Comment by jcoliver** [comment]
@katrinleinweber thanks again for this. Would you update the PR so only the .Rmd files (and not the .md) files are changed?

**Comment by katrinleinweber** [comment]
Do the `.md` changes break Travis' build of `gh-pages`? Since they introduce the exact same changes as in the `.Rmd` files I assumed they would merge & build cleanly.

**Comment by jcoliver** [comment]
@katrinleinweber I _think_ so, but I'll defer to @naupaka . What sort of issues do edited .md files cause during build?

**Comment by naupaka** [comment]
Depends on the modification times because we rely on a makefile. Easiest to just delete the `.md` files so there's no possibility of it thinking it's already built, esp. given merging of other PRs, etc.

**Comment by katrinleinweber** [comment]
I assumed that the modification times of all files become the timestamp of Travis cloning the git repo into its VM. Thus, the makefile would see the same timestamp for both `.md` & `.Rmd` files anyway.

**Comment by jcoliver** [comment]
Thanks, @katrinleinweber!

**Comment by katrinleinweber** [comment]
You're welcome :-)

**Comment by naupaka** [comment]
Looks great, thanks!

**Pull request merged**
