### PR TITLE
added solutions to Challenges in Intro to R and RStudio

### PR DESCRIPTION
**Pull request by marcsze**
Hello,

As part of instructor training we were asked to submit a pull request.  For the proposed changes to this lesson I have added solutions with brief explanations for each of the challenges in the lesson.

Thank you for your time.
Sincerely,
Marc

### CODE REVIEW

**Comment by naupaka** [comment]
Thanks for the PR @marcsze. For pull requests we request that you only submit the `.Rmd` (full details about how we request people modify and contribute to these lessons are [here](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/README.md) and [here](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/CONTRIBUTING.md)), and then I or the other maintainers will generate the markdown and html from that when we rebuild the materials (usually ever few weeks or so). So, I'd ask that you either remove the `.md` and `.html` files from the PR or else submit a new one with just the `.Rmd` file. It helps keep the repository and the commit history clean. Thanks!

**Comment by marcsze** [comment]
Hey @naupaka please let me know if this was an okay way of going about getting only the Rmd file committed.  If not I think I'll close this pull request and just make a new one with only the .Rmd in it.

Marc

**Comment by naupaka** [comment]
Hi @marcsze the other files are still showing up in the PR. If it's easier, it's no hassle for me to close this PR and then respond to your opening a new one.

**Comment by marcsze** [comment]
@naupaka that sounds good to me it would be really easy on my end as well to do it this way

**Comment by naupaka** [comment]
Ok I'll close this one and look for your next PR.

**Pull request closed without merging**
