### PR TITLE
Update from template

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by naupaka** [comment]
This is a ton of stuff. Should we just auto-merge these? Any reason not to? Or is any other discussion needed?

**Comment by gvwilson** [comment]
It should just merge cleanly...

**Comment by r-gaia-cs** [comment]
@gvwilson You are bring all the history of template.

**Comment by gvwilson** [comment]
...which is weird, because this repo was started in the usual way.

**Comment by naupaka** [comment]
Well the (empty) master branch was, but the content on the gh-pages branch is all imported from the COMBINE repo, which might explain why it's pulling over the history since it didn't a recent shared commit...

**Comment by r-gaia-cs** [comment]
@gvwilson The long list of commits is because is the first time that https://github.com/swcarpentry/styles/ is included here. +1 to merge.

**Comment by naupaka** [comment]
Ok, will merge. Thanks for input, @r-gaia-cs @gvwilson

**Pull request merged**
