### PR TITLE
Changes from the last bootcamp

### PR DESCRIPTION
**Pull request by sritchie73**
Major changes that have been made:

 - ggplot2 lesson is hopefully clearer in its explanations
 - ggplot2 lesson is now written as Rmarkdown
 - Packrat and ProjectTemplate have been removed from the lessons (See Issue #3 )
 - Functions lesson now uses the examples from r-novice-inflammation
 - Various cuts to quite a few lessons.

### CODE REVIEW

**Comment by hdashnow** [comment]
We found the workshop ran a lot more smoothly by cutting some of the material that is less relevant to beginners. Quite a lot of the "under the hood" stuff was removed. We still didn't manage to fit in dplyr (even though we had almost 7 hours of teaching time over 2 days), but everything else went reasonably well and wasn't too rushed.

**Comment by naupaka** [comment]
There are a ton of changes in this PR, but since we haven't started really making a bunch of changes yet here, I don't see why we shouldn't just merge them in as-is and use this as the new base for the lessons. Removing packrat also conveniently deals with issue #3. That said, perhaps that packrat material could be stuck in a supplementary lesson somewhere, for intermediate workshops that might have time to get into it? 

I also see that a lot of the changes in the diff are due to differences in smart vs straight quotes, and various slightly different HTML encodings of special characters. Does SWC have a position on quote types and HTML encoding vs ASCII, @jdblischak?

I am inclined to merge this soon, before people start working on them for the Mozilla Science Labs sprint at the end of this week (June 4-5).

cc @aammd @tomwright01

**Comment by sritchie73** [comment]
@naupaka I'll delete the HTML files at the beginning of the mozsprint when I convert the lessons to R markdown.

**Comment by hdashnow** [comment]
@naupaka <https://github.com/naupaka>, I agree. Let's merge and use it as a
new base.

On Tue, Jun 2, 2015 at 8:49 AM, Scott Ritchie <notifications@github.com>
wrote:

> @naupaka <https://github.com/naupaka> I'll delete the HTML files at the
> beginning of the mozsprint when I convert the lessons to R markdown.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/r-novice-gapminder/pull/15#issuecomment-107739890>
> .
>



-- 
Harriet Dashnow
President, COMBINE <http://combine.org.au/>
BSc, BA, MSc (Bioinformatics), PhD candidate
au.linkedin.com/in/hdashnow

**Comment by aammd** [comment]
I agree, merge it in and let's work from here. 

In advance of the Sprint, let's do the outline that Greg suggested. I can volunteer to draft it (unless somebody already did somewhere?)

**Comment by naupaka** [comment]
Merged in the spirit of keeping things rolling along before the sprint.

**Pull request merged**
