### PR TITLE
Add alpha function description

### PR DESCRIPTION
**Pull request by tem11010**
Add alpha function description to Challenge 5.

### CODE REVIEW

**Comment by tem11010** [comment]
I've added a brief description of the alpha function to the challenge 5.

**Comment by naupaka** [comment]
Thanks! 3 quick things to fix:

1. Modify challenge five to state the goal of adding transparency to the plot (currently it's not included in the challenge itself).
2. I think it's technically an `alpha` *parameter* instead of the `alpha` *function*. 
3. Add a period at the end of the added sentence.

**Comment by tem11010** [comment]
Great. How's that?

**Comment by naupaka** [comment]
Looks good. Merging.

**Pull request merged**
