### PR TITLE
added RStudio webinar links for data wrangling and Rmarkdown

### PR DESCRIPTION
**Pull request by bbest**
Per the [Instructor Training: Checkout Procedure](http://swcarpentry.github.io/instructor-training/checkout/), I've improved this repo by adding a few useful resources to the final lessons.

### CODE REVIEW

**Comment by naupaka** [comment]
Thanks for the PR @bbest. I think the addition of the links to resources is useful. I'd ask that you remove the `.Rproj` file and modifications to `.gitignore` before I merge this. I also think you can remove the "- RStudio" from the end of the links. It doesn't seem necessary and is not appended to the earlier links that point to RStudio resources.

**Comment by bbest** [comment]
Thanks @naupaka! As I'm sure you see from above commit https://github.com/swcarpentry/r-novice-gapminder/pull/175/commits/a61c4fbc50e7dfea11169d3c657b24220df0ea95 message:

> removed *.Rproj and reverted .gitignore per @naupaka request in #175

**Comment by naupaka** [comment]
Thanks for those changes. Can you also remove " – RStudio" from the end of the links you added? It doesn't seem necessary.

**Comment by bbest** [comment]
Righto, sorry to have not done that previously

**Comment by naupaka** [comment]
Looks good, thanks for changes!

**Pull request merged**
