### PR TITLE
Add challenge about matrices

### PR DESCRIPTION
**Pull request by fernandomayer**
Proposed challenge for the instructor training wrap up

### CODE REVIEW

**Comment by naupaka** [comment]
Hi @fernandomayer thanks for the PR. Two things came to mind: 

One is that I think it's easier if we avoid TeX in them when possible, to reduce dependencies, and since the primary output of these documents is the web. 

Second, lines only break if there are multiple (4, I believe) whitespace characters at the end of the line. This is important to get your list of possible challenge answers to display correctly. Alternatively, use markdown ordered list syntax, which requires a period instead of a close parentheses after the number.

**Comment by fernandomayer** [comment]
Hi @naupaka, thanks for the input.

I've made a second commit (f07a38) removing the TeX input (using an R output instead), and fixed the markdown list by using period instead of parenthesis. (The list with parenthesis I've copied from the first challenge).

Hope this renders properly now.

Thanks.

**Comment by naupaka** [comment]
Thanks for the fixed @fernandomayer. We have had some additional changes to the same lesson you changed since you initially submitted your PR. Would you mind updating your changes based on the current version of the lesson? And, while you're at it, could you fix the list for Challenge 1? The ordered with with parentheses doesn't render properly (although the list from the challenge you added now looks fine, thanks for fixing that).

**Comment by fernandomayer** [comment]
Hi @naupaka 

I've merged the new changes and kept my challenge at the end of the lesson.

I've also fixed two small typos that I saw while merging.

I didn't see any list in Challenge 1 in this revision, so I'm not sure what I was supposed to do about it.

Anyway, let me know if anything else is needed here.

Thanks.

**Comment by naupaka** [comment]
That must have been on a prior version of this lesson. In any case, thanks for the fixes, and for the PR!

**Pull request merged**
