### PR TITLE
Replace stopifnot() with assert_that() for better error messages

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

What are your feeling/ideas/suggestions regarding replacing [`stopifnot()` in ep. 10](https://github.com/swcarpentry/r-novice-gapminder/blob/f3d5c959a39de2b4d9d9f6927523e8a969427004/_episodes_rmd/10-functions.Rmd) with [`assertthat::assert_that()`](https://github.com/hadley/assertthat#assertthat)?

This topic came up during a workshop preparation and is related to https://github.com/swcarpentry/r-novice-gapminder/issues/221. Over in [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation/search?q=stopifnot&unscoped_q=stopifnot), we don't teach it, and [previous plans to do it were decided against](https://github.com/swcarpentry/r-novice-inflammation/commit/a8a0c7326ea41aaae542806b15bb63c3bdecd3bb).

This is a quick draft, feedback welcome!

### CODE REVIEW

**Comment by naupaka** [comment]
We had a discussion about this a few years ago when `stopifnot()` was added (https://github.com/swcarpentry/r-novice-gapminder/issues/221). The sense then was that it was probably better to stick to a simple base R approach to emphasize defensive programming, instead of adding in another dependency since introducing the concept of unit tests (i.e. `testthat`) in reasonable detail would add a lot of content to already full materials... But perhaps `assertthat()` is reasonable update? @jcoliver @mawds?

**Comment by jcoliver** [comment]
The value of `assertthat` is in the error messages:

`stopifnot`:
> Error: is.numeric(temp) is not TRUE

`assertthat`:
> Error: temp is not a numeric or integer vector

The syntax between the two is identical, so my question is: does the slightly more informative error message justify the cost of the added dependency?

**Comment by katrinleinweber** [comment]
An additional benefit is the reminder to load the `library()` command. That plus the better readability of errors weighs more, than any risk this "dependency" might introduce. What could the risk be _at worst_? We're not running a commercial web app here, where each hour downtime causes lost profits ;-)

If this changes proves useful, we could later turn it into an opportunity to introduce the `::` operator, or show how `install.packages()` can handle a vector.

**Comment by naupaka** [comment]
@katrinleinweber we've (cc @jcoliver @mawds) discussed this and would like to add it as a tip instead of changing the code in the lesson. It is a better function than `stopifnot()`, but the improvement is not so dramatic to overcome the downside of having another dependency (with the many lessons maintained by the Carpentries and all the automated build systems and different versions of R on Travis, locally and etc flying around it's best to avoid additional complexity when possible. 

Would you be willing to update the PR to make it a callout tip instead?

**Comment by jcoliver** [comment]
We're going to close this for now, but if there is an interest in adding `assertthat()` as a callout tip, please feel free to re-open.

**Pull request closed without merging**
