### PR TITLE
Fix issue187

### PR DESCRIPTION
**Pull request by lmsimp**
I have added a few new lines of code in this branch as suggested by issue #187 to address downloading the gap minder data, and fixed the URL in issue #173 in [section 5 data structures part 2](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/). 

This is also to fulfil part I of the checkout procedure for the SWC instructors training (attended Cambridge 19/20th September).

### CODE REVIEW

**Comment by lmsimp** [comment]
Yes, @ashander agreed no strong reason so have changed the URL as suggest in #172

**Comment by ashander** [comment]
Great, it seems this issue has been discussed a number of different places. Hopefully the maintainers agree with our interpretation and it's to finally fix it :)

One thing: the second instance of the URL should also be changed: https://github.com/swcarpentry/r-novice-gapminder/pull/204/files#diff-2267c0f189e8cda7f265c0981ca5c273R269

After that it looks good to me

**Comment by lmsimp** [comment]
@ashander sorry I missed that URL! Now changed in the above commit. In reference to issue #206 yes I believe the only .Rmd needs changing looking at the Makefile. I believe the maintainers regenerate everything following PR and changes.

**Comment by naupaka** [comment]
Hi @lmsimp thanks for this! Could you also remove the `.md` file from the PR? They can cause issues with the makefile we use to generate the pages.

**Comment by lmsimp** [comment]
Hi @naupaka I have removed my updated `.md` . Would you like me to add back in the original unchanged to this PR? Or will you regenerate anyway? Thanks.

**Comment by naupaka** [comment]
No need to re-add, since the markdown gets generated when I rebuild the site. Thanks for the PR! Closes #173 and #187

**Comment by snamburi3** [comment]
The episode 5 - "Exploring Dataframes" is missing from the main [site](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/.) . The .md file does not exist in the episodes/ folder.

**Comment by naupaka** [comment]
Thanks for catching that. Must have been a snag during the site rebuilding with the makefile. I'll work on redoing that ASAP.

**Pull request merged**
