### PR TITLE
Issue 120 - Swap 07-functions / 10-control-flow

### PR DESCRIPTION
**Pull request by marcsze**
We created two new .Rmd files where the old lesson 7 (functions) is now lesson 10 and the old lesson 10 (control flow) is now lesson 7.

### CODE REVIEW

**Comment by tomwright01** [comment]
This causes a small problem with 09-vectorisation. The solution to challenge 4 in that file suggests using functions. I think the extra parts to the solution could be removed.

Also index.md and reference.md will need updating. That's going to cause conflicts with PR #129.

**Comment by marcsze** [comment]
@tomwright01 for issue #120 I updated the requested files and will look at the problem with 09-vectorisation.

**Comment by marcsze** [comment]
@tomwright01 made the change for the small problem with challenge 4 in lesson 9 now as well. Most are in #120 but this last one is part of #137 as well.

**Comment by tomwright01** [comment]
This looks great, I'm going offline for an hour or so. If no-one else comments I'll merge when I get back.

**Comment by marcsze** [comment]
@tomwright01 sounds good to me. Let me know if you need anything else.

**Pull request merged**
