### PR TITLE
Fixed diagrammeR plots, load .png #63

### PR DESCRIPTION
**Pull request by remi-daigle**

### CODE REVIEW

**Comment by naupaka** [comment]
@remi-daigle it looks like you make these changes on an old commit. Can you pull first and then add your changes on top of it? Otherwise I can't auto-merge and it will be nasty to dissect through things... Thanks!

**Comment by naupaka** [comment]
To address issue #63

**Comment by remi-daigle** [comment]
Oops! Sorry about that, I went a little too fast, it should work now with the new commit

**Comment by naupaka** [comment]
Excellent. Thanks! Merging now.

**Pull request merged**
