### PR TITLE
update links

### PR DESCRIPTION
**Pull request by ldutoit**
The links were broken. I suggest a new link for "return" and remove the link for body as it was not working and I did think find it added much value. I started by looking for another link for body but I could not find one.

I suggest these changes as part of checkout

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

### CODE REVIEW

**Comment by jcoliver** [comment]
Thanks for the PR, @ldutoit . Before we accept the changes, I want to double check with @naupaka about what those links were _supposed_ to reference. The resources may still be in the repository, they just might have moved...

**Comment by naupaka** [comment]
@jcoliver yes, good question. I think the links were supposed to be internal links to those sections, and they may be broken because of Jekyll changes or parsing script issues. I think we'd like to fix rather than change/delete them if possible.

@fmichonneau -- are those links the right way to link to internal sections with the current syntax? 

e.g. 

```
[body]({{ page.root }}/reference/#function-body)
```

**Comment by jcoliver** [comment]
The correct links would be:

`[body]({{ page.root }}/reference.html#function-body`
Renders as: http://swcarpentry.github.io/r-novice-gapminder/reference.html#function-body

`[body]({{ page.root }}/reference.html#return-statement`
Renders as: http://swcarpentry.github.io/r-novice-gapminder/reference.html#return-statement

**Comment by naupaka** [comment]
Closing due to subsequent infrastructure changes.

**Pull request closed without merging**
