### PR TITLE
Revisión de traducción del episodio 7

### PR DESCRIPTION
**Pull request by kevinalquicira**
La revisión se realizó entre @imartflo y Yo.
La revisión consistió en correcciones gramaticales, ortografía, estilo y formato. Se terminó la traducción de la mitad del episodio.

### CODE REVIEW

**Comment by ErinBecker** [comment]
@kevinalquicira - Thank you for your contribution. Please submit your PR to the Spanish version of this lesson: https://github.com/Carpentries-ES/r-novice-gapminder.

**Comment by naupaka** [comment]
I think this is the wrong place for this PR. Has it also been going elsewhere, and so can I close this? Don't want to shut it down if it hasn't yet been redirected, but it is not going to ever be merged into this repo, correct?

@kevinalquicira @imartflo @ErinBecker

**Comment by ErinBecker** [comment]
@naupaka  - yes. This PR should be going to a different repo. I'm not sure exactly of the address of that repo, however. @orchid00 @Helysalgado could you please advise?

**Comment by ErinBecker** [comment]
It looks like it should be going here: https://github.com/Carpentries-ES/r-novice-gapminder

@naupaka - please go ahead and close. @kevinalquicira could you please move these commits to that repository? I'm happy to help, just please let me know!

**Comment by naupaka** [comment]
OK, closing.

**Pull request closed without merging**
