### PR TITLE
added alt text

### PR DESCRIPTION
**Pull request by brynnelliott**
added alt text for https://swcarpentry.github.io/r-novice-gapminder//fig/rmd-09-ch2-sol-2.png

### CODE REVIEW

**Comment by ErinBecker** [comment]
I think the check failure was due to https://github.com/carpentries/styles/issues/641 and will be fixed with https://github.com/zkamvar/2022-10-20-workflow-bug/blob/main/update-workflows.R which will be deployed today.

**Comment by zkamvar** [comment]
Note: it will not be fixed until https://github.com/swcarpentry/r-novice-gapminder/pull/806 is merged, but even then, because of the way pull requests work, it will still fail after 806 is merged (sorry it's complicated).

**Comment by zkamvar** [comment]
Luckily, your PR is not complex and it will not break anything as long as the maintainer confirms that the syntax is correct.

**Comment by naupaka** [comment]
LGTM

**Pull request merged**
