### PR TITLE
Add line for appropriate Tip formatting

### PR DESCRIPTION
**Pull request by jcoliver**
The second Tip in the lesson (any and all) was not being formatted correctly.  I added an empty line between the tip header and content in an effort to get the formatting to work (thumb-tack image, blue box, etc.).

### CODE REVIEW

**Comment by tomwright01** [comment]
@jcoliver Unfortunately inserting the empty line didn't solve the problem. I think it's the back-ticks in the title that are causing the problem. If there isn't a nicer way these could just be removed.

**Comment by jcoliver** [comment]
@tomwright01 Got it.  I just removed the back-ticks.

**Comment by jcoliver** [comment]
Ah.  Hold off on the PR.  Was still using a branch where control flow was lesson 10...

**Comment by naupaka** [comment]
Looks good, thanks.

**Pull request merged**
