### PR TITLE
adding a link to an online book as a ressource

### PR DESCRIPTION
**Pull request by bervelin-lumesa**
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._

_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._

_If any relevant discussions have taken place elsewhere, please provide links to these._

<details>

For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).

Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

</details>

### CODE REVIEW

**Review by skanwal — APPROVED** [review]
Thank you. Seems like a great resource.

**Comment by naupaka** [comment]
I agree this is a nice addition and should be good to merge, but it looks like one of the automated checks is failing. I am not sure what the error is referring to - perhaps @froggleston would have a better sense? It seems like a very simple/straightforward PR.

**Comment by froggleston** [comment]
This is due to the update-artifact workflow being updated to v4 which needed a subsequent fix that was part of the 0.16.7 release, so this PR perhaps was based on a version of the workflow that is old? If you pull in the new workflow into this PR it should work?

**Comment by naupaka** [comment]
@froggleston yup that did it, thanks!

**Comment by naupaka** [comment]
Thanks @bervelin-lumesa for the contribution!

**Comment by bervelin-lumesa** [comment]
@naupaka you're welcome

**Pull request merged**
