### PR TITLE
Spell check and apply consistent code style (close #548) 

### PR DESCRIPTION
**Pull request by katrinleinweber**
This is an updated version of #548 as per its review. All thanks to @adamhsparks for doing most of the work. I just added a few additional clean-ups and resolved the merge conflicts that appeared since then.

### CODE REVIEW

**Comment by adamhsparks** [comment]
Thanks for this. I've just simply not had time to go back and make the requested changes since I submitted the original PR.

**Comment by jcoliver** [comment]
Thanks @adamhsparks and @katrinleinweber, we are reviewing these changes.

**Comment by katrinleinweber** [comment]
I applied the changes of 3bca74ba7195df1f98814a20d0f74b46af120fdd, but in order to keep it aligned with the above-taught `labs(y = ...)`:

**Comment by jcoliver** [comment]
We are closing this for now, given changes to episodes that are in progress due to the update to R 4.0. Please feel free to revisit if warranted.

**Pull request closed without merging**
