### PR TITLE
while statement clarifications

### PR DESCRIPTION
**Pull request by jpiaskowski**
Some edits designed to address ambiguity for the lesson on while statements and also to align the wording with common approaches to discussing entry controlled flow statements. 

This addresses r-novice-gapminder issue 459:

https://github.com/swcarpentry/r-novice-gapminder/issues/459

### CODE REVIEW

**Comment by jcoliver** [comment]
This looks great, @jpiaskowski . One minor change would be to leave the loop body of the pseudocode block unchanged. Would you mind updating your PR with the original loop body? i.e.
```
while(this condition is true){
   do a thing
}
```

**Comment by jpiaskowski** [comment]
I can't figure how to do this. The right buttons to submit a pull request never seem to light up. I don't know what I'm doing wrong.

**Comment by jcoliver** [comment]
You're doing fine, @jpiaskowski . The PR looks good. Will merge soon.

**Comment by jcoliver** [comment]
Thanks again for this, @jpiaskowski .

**Pull request merged**
