### PR TITLE
Minor text edits for spelling & clarity

### PR DESCRIPTION
**Pull request by Alex-A14**
Hi,

I did a quick read through of the `knitr` lesson and noticed some spelling mistakes. I also made some wording changes that I think make the text clearer.

The only major change was to remove the text at line 110 because I couldn't see what it was referring to in the document. Maybe I missed something.

Hope this helps! Let me know if I can change anything.

### CODE REVIEW

**Comment by jcoliver** [comment]
Thanks for this PR, @Alex-A14 . Would you mind updating the PR to use the `<kbd>` tag system for referring to keystrokes? The addition of the shortcuts on line 256 is great, and the `<kbd>` tags provide formatting option, e.g. 
```
<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>
``` 
The RMarkdown for Episode 1 has multiple examples of the use of `<kbd>`: https://github.com/swcarpentry/r-novice-gapminder/blob/master/_episodes_rmd/01-rstudio-intro.Rmd

**Comment by Alex-A14** [comment]
Done! I think that was the only example? Let me know if I missed any other keystrokes

**Comment by jcoliver** [comment]
Thanks, @Alex-A14 . I think the shortcut for creating on new chunk on Windows/Linux is Ctrl+Alt+I, though.

**Comment by Alex-A14** [comment]
My bad; made a mistake copy and pasting.

**Comment by jcoliver** [comment]
Been there more times than I care to admit. Thanks again, @Alex-A14 .

**Pull request merged**
