### PR TITLE
Added an easy challenge to lesson 7 (functions)

### PR DESCRIPTION
**Pull request by elisemorrison**
Added an easy challenge (Challenge #4) to address issue #22:  Add more easy challenges

### CODE REVIEW

**Comment by naupaka** [comment]
Hi @elisemorrison thanks for the PR. Can you also add in a solution to the challenge? These generally go at the end of the lesson.

**Comment by elisemorrison** [comment]
Thanks @naupaka.  I've added the solution to challenge #4

**Comment by naupaka** [comment]
Thanks @elisemorrison. One more thing to fix -- for the answers to break across lines in markdown, they need to end in two or more spaces. Can you add these to your answer section?

**Comment by naupaka** [comment]
Hi @elisemorrison just a quick check in to see if you can make those minor changes to the R markdown file. I just noticed that you edited the `.md` file instead of the `.Rmd`. Once we regenerate the web pages for these lessons, all `.md` files will get overwritten, so we ask that all contributors only edit the `.Rmd`. Let me know - if not I will close this PR since there hasn't been activity on it in the past few months.

**Comment by gvwilson** [comment]
@naupaka would you be comfortable merging, making the line-break fix, and then pushing your changes?

**Pull request merged**
