### PR TITLE
name of dir needs an s as the instruction

### PR DESCRIPTION
**Pull request by orchid00**
should be scripts dir

### CODE REVIEW

**Comment by naupaka** [comment]
@orchid00 thanks for the PR! That indeed needs to be fixed. However, it looks like you made a change to the markdown files instead of the `Rmd`. Can you update the PR to modify the Rmd instead?

**Comment by orchid00** [comment]
Done, 

@naupaka if you have a few min, could you please shortly explain me why do we have md if the Rmd is the one rendered for the site?

**Comment by naupaka** [comment]
So we use a (GitHub provided through [GitHub pages](https://pages.github.com/)) static website renderer called [Jekyll](https://jekyllrb.com/) that turns the markdown files into html, which is what people see when they go to the rendered lessons. The problem is that Jekyll can't parse Rmd files, so those have to be converted locally (we use `rmarkdown::render()`) by the maintainers using the Makefile in the repository. So I or one of the other maintainers pull down all the new changes that people have contributed, then convert them from Rmd to markdown, then push that back to GitHub, which then is set up to render the markdown files into the final html web pages.  This process overwrites any existing markdown, which is why it's important for the changes to happen to the Rmd files. As for why Rmd instead of md, it's because it ensures that the code and the output of the code don't get out of sync or have to be copied into the output sections since the output is generated from the code directly when it is rendered by the rmarkdown package.

Hope that helps clarify a bit? We also have some info on how that all happens for the Carpentry lesson [in this lesson example module](http://swcarpentry.github.io/lesson-example/).

**Comment by naupaka** [comment]
Closed per #337

**Comment by orchid00** [comment]
Thank you @naupaka!

**Pull request closed without merging**
