### PR TITLE
fix one erratum

### PR DESCRIPTION
**Pull request by prosoitos**
factors *are* vectors (can be verified by testing a factor x with `is.atomic(x) || is.list(x)` as per http://adv-r.had.co.nz/Data-structures.html)

### CODE REVIEW

**Comment by jcoliver** [comment]
Thanks, @prosoitos . This sounds good to me - any objections @mawds @naupaka @tomwright01 ?

**Comment by prosoitos** [comment]
To add more info, according to http://127.0.0.1:25436/library/base/html/factor.html, "factor" is the "class" of the object (as "character" or "double"). And according to http://r4ds.had.co.nz/vectors.html, "factors" are "augmented vectors built on top of integer vectors".

**Comment by naupaka** [comment]
I am 100% in support of this change.

**Comment by prosoitos** [comment]
Great. Thank you all! I am in the middle of my Carpentry instructor training and I spotted other little issues in this lesson. So I will send another PR with other little suggestions later. Apologies for not doing them all at once!

**Comment by naupaka** [comment]
@prosoitos No worries! Actually we prefer them this way - it keeps the PRs focused and easy to review.

**Comment by prosoitos** [comment]
Ok. Good to know.

**Pull request merged**
